server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 0
  servlet:
    session:
      cookie:
        secure: true
      timeout: 0
    context-path: /
spring:
  profiles:
    active: prod
  # HTTP 配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 文件存放地址
  file:
    remoteJspPath: /home/rb/tomcat/iptv_hd/
    remoteActImgPath: /home/rb/web/iptv_hd/images/HD/activities/
    remoteActIconPath: /home/rb/web/iptv_hd/images/HD/photos/recommend/index/
    remoteActFiconPath: /home/rb/web/iptv_hd/images/HD/photos/recommend/index/focus/
    remoteEnterIconPath: //home/rb/web/iptv_hd/images/HD/common/enter/
    tempResourcePath: D:\工作\img\
    tempJspPathProd: D:\projects\generate-union\generate\src\main\resources\tempJsp\prod\
    tempJspPathTest: D:\projects\generate-union\generate\src\main\resources\tempJsp\test\
    tempReportPath: D:\projects\generate-union\generate\src\main\resources\tempReport\
    songTestTempFile: D:\projects\generate-union\generate\src\main\resources\songTest\temp\testTemp.jsp
    songTestPath: D:\projects\generate-union\generate\src\main\resources\songTest\
  #配置日志
  logging:
    #配置日志文件路径
    level:
      org.springfromework.web: debug
      org.hibernate: debug
      cn.reco.generate: debug
