server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 0
  servlet:
    session:
      cookie:
        secure: true
      timeout: 0
    context-path: /
spring:
  profiles:
    # 陕西广电 测试：sxgdTest, 生产：sxgdProd
    # 陕西电信 测试：sxdxTest, 生产：sxdxProd
    active: sxgdTest
  # HTTP 配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #配置日志
  logging:
    #配置日志文件路径
    level:
      org.springfromework.web: debug
      org.hibernate: debug
      cn.reco.generate: debug
